In [7]:
# Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
#get some data
df = pd.read_parquet("../data/BOQ_data.parquet")

df

,A2ME,BEME,BEME_adj,BEME_ind,CEI,DATE,DEC_ME,DEC_SHROUT,Div,Div_ann,...,s2invt,s2rect,sale,sale_ind,sales_g,sga2s,spread_mean,std_turn,std_vol,suv
0,NaN,NaN,NaN,0.824752,NaN,1986-01-31,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,0.825905,NaN,1986-02-28,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.076998,0.212080,7.804561e+03,NaN
2,NaN,NaN,NaN,0.825905,NaN,1986-03-31,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.055511,0.107977,3.973568e+03,-0.363314
3,NaN,NaN,NaN,0.825015,NaN,1986-04-30,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.037231,0.174533,6.422826e+03,-0.571056
4,NaN,NaN,NaN,0.824672,NaN,1986-05-31,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.048336,0.150228,5.527503e+03,-0.708679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3568650,0.211263,0.114912,-0.746238,0.861151,-12.189408,2023-08-31,3.897415e+08,3164000.0,0.0,0.0,...,6.344887,26.084534,81462.0,579615.973,0.513517,0.086187,0.000152,0.708916,2.250092e+07,-1.580970
3568651,0.211263,0.114912,-0.750723,0.865635,-11.613183,2023-09-30,3.897415e+08,3164000.0,0.0,0.0,...,6.344887,26.084534,81462.0,579615.973,0.513517,0.086187,0.000133,0.465122,1.476294e+07,-0.371920
3568652,0.211263,0.114912,-0.731231,0.846143,-12.752123,2023-10-31,3.897415e+08,3164000.0,0.0,0.0,...,6.344887,26.084534,81462.0,579615.973,0.513517,0.086187,0.000177,0.531342,1.686876e+07,0.809301
3568653,0.211263,0.114912,-0.731231,0.846143,-7.943286,2023-11-30,3.897415e+08,3164000.0,0.0,0.0,...,6.344887,26.084534,81462.0,579615.973,0.513517,0.086187,0.000245,0.614813,1.954419e+07,0.278301
3568654,0.211263,0.114912,-0.731231,0.846143,-9.359996,2023-12-31,3.897415e+08,3164000.0,0.0,0.0,...,6.344887,26.084534,81462.0,579615.973,0.513517,0.086187,0.000186,0.599491,1.905735e+07,0.967711

In [9]:
# Sort out labels
labels = sorted(df.columns.to_list())

labels

['A2ME',
 'BEME',
 'BEME_adj',
 'BEME_ind',
 'CEI',
 'DATE',
 'DEC_ME',
 'DEC_SHROUT',
 'Div',
 'Div_ann',
 'E2P',
 'EPS',
 'IOR',
 'LME',
 'LME_ind',
 'LTurnover',
 'ME',
 'NumOwners',
 'PERMNO',
 'PRC',
 'Q',
 'RET',
 'ROC',
 'S2P',
 'SICCD',
 'Turnover',
 'VOL',
 'at',
 'at_adj',
 'at_ind',
 'ato',
 'be',
 'beta',
 'beta_daily',
 'beta_sq',
 'c',
 'cash_lt',
 'cto',
 'cum_return_12_2',
 'cum_return_12_7',
 'cum_return_1_0',
 'cum_return_36_13',
 'cum_return_60_1',
 'cum_return_6_2',
 'd2a',
 'd_ceq',
 'dpi2a',
 'fc2y',
 'free_cf',
 'idio_vol',
 'investment',
 'lev',
 'noa',
 'oa',
 'ol',
 'p1_hml_beta',
 'p1_intercept',
 'p1_mktrf_beta',
 'p1_n',
 'p1_smb_beta',
 'p3_intercept',
 'p3_lmktrf_beta',
 'p3_mktrf_beta',
 'p3_n',
 'pcm',
 'pm',
 'pm_adj',
 'prof',
 'rel_to_high_price',
 'ret_max',
 'rna',
 'roa',
 'roe',
 'roic',
 's2c',
 's2invt',
 's2rect',
 'sale',
 'sale_ind',
 'sales_g',
 'sga2s',
 'spread_mean',
 'std_turn',
 'std_vol',
 'suv']

In [10]:
# Clea up the data
clean = df[['DATE', 'PERMNO', 'PRC', 'RET', 'ME']]

clean = clean.rename(columns={'DATE':'date', 'PERMNO': 'permno', 'PRC':'price', 'RET': 'return', 'ME': 'market_cap'})

clean

              date   permno       price    return    market_cap
0       1986-01-31  10000.0    4.375000       NaN  1.610000e+04
1       1986-02-28  10000.0    3.250000 -0.257143  1.196000e+04
2       1986-03-31  10000.0    4.437500  0.365385  1.633000e+04
3       1986-04-30  10000.0    4.000000 -0.098592  1.517200e+04
4       1986-05-31  10000.0    3.109375 -0.222656  1.179386e+04
...            ...      ...         ...       ...           ...
3568650 2023-08-31  93436.0  258.079987 -0.034962  8.191443e+08
3568651 2023-09-30  93436.0  250.220001 -0.030456  7.954494e+08
3568652 2023-10-31  93436.0  200.839996 -0.197346  6.384545e+08
3568653 2023-11-30  93436.0  240.080002  0.195379  7.631954e+08
3568654 2023-12-31  93436.0  248.479996  0.034988  7.898983e+08

[3534205 rows x 5 columns]

In [11]:
# Ensure 'date' is in datetime format
clean['date'] = pd.to_datetime(clean['date'])

# Set 'date' as the index for easier time-based operations
clean.set_index('date', inplace=True)

# Define the cutoff period (2 years from the most recent date in the dataset)
two_years_ago = clean.index.max() - pd.DateOffset(years=2)

# Filter the dataset to keep only rows within the last 2 years
clean = clean[clean.index >= two_years_ago]

# Create a copy of the filtered DataFrame to avoid SettingWithCopyWarning
clean = clean.copy()

# Define the window size for the weighted moving average (3 months of data)
window_size = 3

# Function to calculate a weighted moving average with more recent data receiving higher weights
def weighted_moving_average(values):
    weights = np.arange(1, len(values) + 1)  # Increasing weights for more recent values
    return np.dot(values, weights) / weights.sum()

# Apply the weighted moving average to the 'price' column using .loc for safe assignment
clean.loc[:, 'weighted_moving_avg'] = clean['price'].rolling(window=window_size, min_periods=1).apply(weighted_moving_average, raw=True)

# Display the last 10 rows of the DataFrame with the original 'price' and calculated 'weighted_moving_avg'
print(clean[['price', 'weighted_moving_avg']].tail())

                  price  weighted_moving_avg
date
2022-10-31     0.990000             0.951667
2022-11-30     1.110000             1.006667
2022-12-31     1.490000             1.280000
2023-01-31     1.465000             1.414167
2023-02-28     1.830000             1.651667
2023-03-31     1.445000             1.576667
2023-04-30     1.360000             1.466667
2023-05-31     1.060000             1.224167
2023-06-30     1.220000             1.190000
2023-07-31     1.210000             1.188333
2023-08-31     0.940100             1.076717
2023-09-30     1.120000             1.075033
2023-10-31     0.669700             0.864867
2023-11-30     0.657000             0.738400
2023-12-31     0.700000             0.680617
2021-12-31  1056.780029           528.732848
2022-01-31   936.719971           820.736662
2022-02-28   870.429993           923.584991
2022-03-31  1077.599976           985.063314
2022-04-30   870.760010           939.651662
2022-05-31   758.260010           848.983337
2022-06-30   673.419983           734.589996
2022-07-31   891.450012           796.575002
2022-08-31   275.609985           547.191661
2022-09-30   265.250000           373.069997
2022-10-31   227.539993           248.121661
2022-11-30   194.699997           217.404996
2022-12-31   123.180000           164.413331
2023-01-31   173.220001           160.120000
2023-02-28   205.710007           181.125004
2023-03-31   207.460007           201.170006
2023-04-30   164.309998           185.593335
2023-05-31   203.929993           191.311663
2023-06-30   261.769989           226.246658
2023-07-31   267.429993           254.959991
2023-08-31   258.079987           261.811656
2023-09-30   250.220001           255.708328
2023-10-31   200.839996           226.839996
2023-11-30   240.080002           228.690000
2023-12-31   248.479996           237.739998

In [12]:
# https://stanford.edu/class/msande448/2018/Final/Reports/gr2.pdf

Knowledge:

__I know that I need to measure the correlation between some/all of the stocks so I can use the means of those "sectors" to create signals__

__I need to measure volatility as a measure of risk for my sharpe ratio and determining the size of my securities__

__I need to excecute the trades__


Questions:

__What should the upper and lower signals be? full std dev? half? 150%? if std dev, then what interval lengths am I measuring?__

__Am I able to ascertain sectors using permnos?__

__Is the data every month from 1986 to 2024?__

__Should i test this as a papertrade or just on the given dataset?__

__How do I excecute the trades?__